version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: analytics
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.6.3
    container_name: airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin123@postgres:5432/analytics
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./config:/opt/airflow/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8090:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow webserver &
      airflow scheduler"

  spark:
    image: bitnami/spark:3.3.2
    container_name: spark
    restart: always
    environment:
      - SPARK_MODE=master
      - SPARK_DRIVER_MEMORY=2g
      - SPARK_EXECUTOR_MEMORY=2g
    ports:
      - "7077:7077"
      - "8082:8080"  # Para acessar a UI do Spark
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data  # Pasta para armazenar arquivos temporários
      
networks:
  default:
    name: pswdigital_network

